--PART A

--1A
SELECT * FROM DEPOSIT
--2A
SELECT * FROM BORROW
--3A 
SELECT * FROM CUSTOMERS
--4A
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
--5A
SELECT LOANNO,AMOUNT FROM BORROW
--6A
SELECT * FROM BORROW WHERE BNAME='ANDHERI'
--7A
SELECT ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO=106
SELECT ACTNO AS ACOUNTNO ,AMOUNT FROM DEPOSIT WHERE ACTNO=106
--8A
SELECT CNAME AS CUSTOMERNAME FROM BORROW WHERE AMOUNT>5000
--9A
SELECT CNAME AS CUSTOMERNAME FROM DEPOSIT WHERE ADATE>'1996-12-01'
--10A
SELECT CNAME AS CUSTOMERNAME FROM DEPOSIT WHERE ACTNO<105
--11A
SELECT CNAME AS CUSTOMERNAME FROM CUSTOMERS WHERE CITY='NAGPUR' OR CITY='DELHI'
SELECT CNAME AS CUSTOMERNAME FROM CUSTOMERS WHERE CITY IN ('NAGPUR','DELHI')
--12A
SELECT CNAME , BNAME FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<105
--13A
SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000
SELECT CNAME FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000
--14A
SELECT CNAME FROM DEPOSIT WHERE BNAME<>'ANDHERI'
--15A
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO<104


--PART B

--1B
SELECT TOP 5 *  FROM DEPOSIT 
--2B
SELECT TOP 3 * FROM DEPOSIT WHERE AMOUNT>1000
--3B
SELECT TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME<>'ANDHERI'
--4B
SELECT DISTINCT CITY FROM CUSTOMERS 
--5B
SELECT DISTINCT BNAME FROM BRANCH


--PART C

--1C
SELECT TOP 50 PERCENT * FROM BORROW
--2C
SELECT TOP 10 PERCENT AMOUNT FROM DEPOSIT
--3C
SELECT TOP 25 PERCENT CNAME FROM DEPOSIT WHERE AMOUNT>5000
--4C
SELECT TOP 10 PERCENT AMOUNT FROM BORROW
--5C
SELECT DISTINCT CNAME , CITY FROM CUSTOMERS
--6C
SELECT * ,(AMOUNT+0.1) FROM BORROW
--+0.1 atle cuz 1/10 (10% kairu)
--7C
SELECT * FROM BORROW WHERE (LOANNO%2=1)--ODD
SELECT * FROM BORROW WHERE (LOANNO%2=0)--EVEN
